# Generated by Django 3.2.5 on 2021-08-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('brand', models.CharField(max_length=75)),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('sale_active', models.BooleanField(default=False)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
